"""speech_corpus_init

Revision ID: 4246621aa9e1
Revises: 
Create Date: 2026-08-06 14:20:17.043385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4246621aa9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('gender_label', sa.String(), nullable=True),
    sa.Column('pitch_mean', sa.Float(), nullable=True),
    sa.Column('pitch_range', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=True),
    sa.Column('pause_ratio', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('dtw_score_male', sa.Float(), nullable=True),
    sa.Column('dtw_score_female', sa.Float(), nullable=True),
    sa.Column('embedding_score_male', sa.Float(), nullable=True),
    sa.Column('embedding_score_female', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('analysis_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_analysis_user_id'), 'audio_analysis', ['user_id'], unique=False)
    op.create_table('dataset_audio',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender_label', sa.String(), nullable=False),
    sa.Column('pitch_mean', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=True),
    sa.Column('pause_ratio', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('focus_area', sa.String(), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=False),
    sa.Column('target_sentence', sa.Text(), nullable=False),
    sa.Column('estimated_duration_mins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phoneme_statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('phoneme', sa.String(), nullable=False),
    sa.Column('expected_phoneme', sa.String(), nullable=True),
    sa.Column('detected_phoneme', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phoneme_statistics_analysis_id'), 'phoneme_statistics', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_phoneme_statistics_user_id'), 'phoneme_statistics', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('achievement_key', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_learning_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_level', sa.String(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_practice_date', sa.DateTime(), nullable=True),
    sa.Column('completed_tasks_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_phoneme_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('phoneme', sa.String(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('mistake_count', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phoneme_summary_user_id'), 'user_phoneme_summary', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dataset_contour',
    sa.Column('audio_id', sa.String(), nullable=False),
    sa.Column('pitch_contour', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('energy_contour', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pause_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['dataset_audio.id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_table('dataset_feature',
    sa.Column('audio_id', sa.String(), nullable=False),
    sa.Column('pitch_mean', sa.Float(), nullable=True),
    sa.Column('pitch_std', sa.Float(), nullable=True),
    sa.Column('pitch_range', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=True),
    sa.Column('pause_ratio', sa.Float(), nullable=True),
    sa.Column('speech_rate', sa.Float(), nullable=True),
    sa.Column('mfcc', sa.JSON(), nullable=True),
    sa.Column('zcr', sa.Float(), nullable=True),
    sa.Column('spectral_centroid', sa.Float(), nullable=True),
    sa.Column('spectral_bandwidth', sa.Float(), nullable=True),
    sa.Column('spectral_rolloff', sa.Float(), nullable=True),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['dataset_audio.id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_table('dataset_formant',
    sa.Column('audio_id', sa.String(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('f2', sa.Float(), nullable=True),
    sa.Column('f3', sa.Float(), nullable=True),
    sa.Column('vowel_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['dataset_audio.id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_table('learning_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_improvement', sa.Float(), nullable=True),
    sa.Column('ai_coach_feedback', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['learning_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_history_user_id'), 'learning_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_history_user_id'), table_name='learning_history')
    op.drop_table('learning_history')
    op.drop_table('dataset_formant')
    op.drop_table('dataset_feature')
    op.drop_table('dataset_contour')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_phoneme_summary_user_id'), table_name='user_phoneme_summary')
    op.drop_table('user_phoneme_summary')
    op.drop_table('user_learning_progress')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_phoneme_statistics_user_id'), table_name='phoneme_statistics')
    op.drop_index(op.f('ix_phoneme_statistics_analysis_id'), table_name='phoneme_statistics')
    op.drop_table('phoneme_statistics')
    op.drop_table('learning_tasks')
    op.drop_table('global_statistics')
    op.drop_table('dataset_audio')
    op.drop_index(op.f('ix_audio_analysis_user_id'), table_name='audio_analysis')
    op.drop_table('audio_analysis')
    # ### end Alembic commands ###
