"""Add CAPT models

Revision ID: 43ac9132b2f4
Revises: 4246621aa9e1
Create Date: 2026-08-06 15:51:23.242618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ac9132b2f4'
down_revision: Union[str, Sequence[str], None] = '4246621aa9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('ai_teacher_feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_feedback_analysis_id'), 'analysis_feedback', ['analysis_id'], unique=False)
    op.create_table('analysis_intonation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('dtw_distance', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('slope_diff', sa.Float(), nullable=True),
    sa.Column('user_contour', sa.Text(), nullable=True),
    sa.Column('native_contour', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_intonation_analysis_id'), 'analysis_intonation', ['analysis_id'], unique=False)
    op.create_table('analysis_phoneme',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('word_id', sa.String(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('phoneme', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_phoneme_analysis_id'), 'analysis_phoneme', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_phoneme_word_id'), 'analysis_phoneme', ['word_id'], unique=False)
    op.create_table('analysis_pronunciation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('mispronounced_word', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_pronunciation_analysis_id'), 'analysis_pronunciation', ['analysis_id'], unique=False)
    op.create_table('analysis_word',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('pitch_score', sa.Float(), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('duration_score', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_word_analysis_id'), 'analysis_word', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_word_analysis_id'), table_name='analysis_word')
    op.drop_table('analysis_word')
    op.drop_index(op.f('ix_analysis_pronunciation_analysis_id'), table_name='analysis_pronunciation')
    op.drop_table('analysis_pronunciation')
    op.drop_index(op.f('ix_analysis_phoneme_word_id'), table_name='analysis_phoneme')
    op.drop_index(op.f('ix_analysis_phoneme_analysis_id'), table_name='analysis_phoneme')
    op.drop_table('analysis_phoneme')
    op.drop_index(op.f('ix_analysis_intonation_analysis_id'), table_name='analysis_intonation')
    op.drop_table('analysis_intonation')
    op.drop_index(op.f('ix_analysis_feedback_analysis_id'), table_name='analysis_feedback')
    op.drop_table('analysis_feedback')
    # ### end Alembic commands ###
